services:
  - type: web
    name: fake-news-detector
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m nltk.downloader stopwords wordnet omw-1.4"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NEWS_API_KEY
        value: "mock_mode_active"
